@FoodREST.API_HostAddress = https://localhost:7154

### Create a food
POST {{FoodREST.API_HostAddress}}/api/foods
Accept: application/json
Content-Type: application/json

{
  "Name":"Banana",
  "Calories":"110",
  "ProteinGrams":"2",
  "CarbohydrateGrams":"27",
  "FatGrams":"0"
}

###
GET {{FoodREST.API_HostAddress}}/api/foods/a32d589e-96d7-4485-8ce9-682149691a0c