@FoodREST.API_HostAddress = https://localhost:7154

### Create a food
POST {{FoodREST.API_HostAddress}}/api/foods
Accept: application/json
Content-Type: application/json

{
  "Name":"Banana",
  "Calories":"110",
  "ProteinGrams":"2",
  "CarbohydrateGrams":"27",
  "FatGrams":"0"
}

### Get a food
GET {{FoodREST.API_HostAddress}}/api/foods/2fab54d1-1606-4a1b-8f17-b60f68d3669f

### Get all foods
GET {{FoodREST.API_HostAddress}}/api/foods
Accept: application/json

### Update a food
PUT {{FoodREST.API_HostAddress}}/api/foods/2fab54d1-1606-4a1b-8f17-b60f68d3669f
Accept: application/json
Content-Type: application/json

{
  "Name":"Apple",
  "Calories":"95",
  "ProteinGrams":"1",
  "CarbohydrateGrams":"30",
  "FatGrams":"0"
}


### Delete a food
DELETE {{FoodREST.API_HostAddress}}/api/foods/2fab54d1-1606-4a1b-8f17-b60f68d3669f
Accept: application/json